export const SET_AUTHORIZE = 'SET_AUTHORIZE';

export const FETCH_SETTINGS_REQUEST = 'FETCH_SETTINGS_REQUEST';
export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS';
export const FETCH_SETTINGS_ERROR = 'FETCH_SETTINGS_ERROR';

export const SAVE_SETTINGS_REQUEST = 'SAVE_SETTINGS_REQUEST';
export const SAVE_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS';
export const SAVE_SETTINGS_ERROR = 'SAVE_SETTINGS_ERROR';

export const FETCH_MANAGERS_REQUEST = 'FETCH_MANAGERS_REQUEST';
export const FETCH_MANAGERS_SUCCESS = 'FETCH_MANAGERS_SUCCESS';
export const FETCH_MANAGERS_ERROR = 'FETCH_MANAGERS_ERROR';

export const ADD_MANAGER_REQUEST = 'ADD_MANAGER_REQUEST';
export const ADD_MANAGER_SUCCESS = 'ADD_MANAGER_SUCCESS';
export const ADD_MANAGER_ERROR = 'ADD_MANAGER_ERROR';

export const REMOVE_MANAGER_REQUEST = 'REMOVE_MANAGER_REQUEST';
export const REMOVE_MANAGER_SUCCESS = 'REMOVE_MANAGER_SUCCESS';
export const REMOVE_MANAGER_ERROR = 'REMOVE_MANAGER_ERROR';

export const FETCH_DIALOGS_REQUEST = 'FETCH_DIALOGS_REQUEST';
export const FETCH_DIALOGS_SUCCESS = 'FETCH_DIALOGS_SUCCESS';
export const FETCH_DIALOGS_ERROR = 'FETCH_DIALOGS_ERROR';

export const LOADER_ON = 'LOADER_ON';
export const LOADER_OFF = 'LOADER_OFF';

export const FETCH_DIALOG_REQUEST = 'FETCH_DIALOG_REQUEST';
export const FETCH_DIALOG_SUCCESS = 'FETCH_DIALOG_SUCCESS';
export const FETCH_DIALOG_ERROR = 'FETCH_DIALOG_ERROR';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const SOCKET_ROOMS_CHANGED_EVENT = 'SOCKET_ROOMS_CHANGED_EVENT';

export const LOADER_TURN_OFF = 'LOADER_TURN_OFF';

export const FETCH_ROLE_REQUEST = 'FETCH_ROLE_REQUEST';
export const FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS';
export const FETCH_ROLE_ERROR = 'FETCH_ROLE_ERROR';

export const FETCH_REQUESTS_REQUEST = 'FETCH_REQUESTS_REQUEST';
export const FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS';
export const FETCH_REQUESTS_ERROR = 'FETCH_REQUESTS_ERROR';

export const DELETE_REQUEST_REQUEST = 'DELETE_REQUEST_REQUEST';
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS';
export const DELETE_REQUEST_ERROR = 'DELETE_REQUEST_ERROR';