export const SET_AUTHORIZE = 'SET_AUTHORIZE';

export const FETCH_SETTINGS_REQUEST = 'FETCH_SETTINGS_REQUEST';
export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS';
export const FETCH_SETTINGS_ERROR = 'FETCH_SETTINGS_ERROR';

export const SAVE_SETTINGS_REQUEST = 'SAVE_SETTINGS_REQUEST';
export const SAVE_SETTINGS_SUCCESS = 'SAVE_SETTINGS_SUCCESS';
export const SAVE_SETTINGS_ERROR = 'SAVE_SETTINGS_ERROR';

export const FETCH_MANAGERS_REQUEST = 'FETCH_MANAGERS_REQUEST';
export const FETCH_MANAGERS_SUCCESS = 'FETCH_MANAGERS_SUCCESS';
export const FETCH_MANAGERS_ERROR = 'FETCH_MANAGERS_ERROR';

export const ADD_MANAGER_REQUEST = 'ADD_MANAGER_REQUEST';
export const ADD_MANAGER_SUCCESS = 'ADD_MANAGER_SUCCESS';
export const ADD_MANAGER_ERROR = 'ADD_MANAGER_ERROR';

export const REMOVE_MANAGER_REQUEST = 'REMOVE_MANAGER_REQUEST';
export const REMOVE_MANAGER_SUCCESS = 'REMOVE_MANAGER_SUCCESS';
export const REMOVE_MANAGER_ERROR = 'REMOVE_MANAGER_ERROR';

export const FETCH_DIALOGS_REQUEST = 'FETCH_DIALOGS_REQUEST';
export const FETCH_DIALOGS_SUCCESS = 'FETCH_DIALOGS_SUCCESS';
export const FETCH_DIALOGS_ERROR = 'FETCH_DIALOGS_ERROR';

export const LOADER_ON = 'LOADER_ON';
export const LOADER_OFF = 'LOADER_OFF';

export const FETCH_DIALOG_REQUEST = 'FETCH_DIALOG_REQUEST';
export const FETCH_DIALOG_SUCCESS = 'FETCH_DIALOG_SUCCESS';
export const FETCH_DIALOG_ERROR = 'FETCH_DIALOG_ERROR';

export const FETCH_HISTORY_REQUEST = 'FETCH_HISTORY_REQUEST';
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS';
export const FETCH_HISTORY_ERROR = 'FETCH_HISTORY_ERROR';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const FETCH_CLIENT_INFO_REQUEST = 'FETCH_CLIENT_INFO_REQUEST';
export const FETCH_CLIENT_INFO_SUCCESS = 'FETCH_CLIENT_INFO_SUCCESS';
export const FETCH_CLIENT_INFO_ERROR = 'FETCH_CLIENT_INFO_ERROR';

export const FETCH_MANAGER_INFO_REQUEST = 'FETCH_MANAGER_INFO_REQUEST';
export const FETCH_MANAGER_INFO_SUCCESS = 'FETCH_MANAGER_INFO_SUCCESS';
export const FETCH_MANAGER_INFO_ERROR = 'FETCH_MANAGER_INFO_ERROR';

export const SOCKET_ROOMS_CHANGED_EVENT = 'SOCKET_ROOMS_CHANGED_EVENT';

export const LOADER_TURN_OFF = 'LOADER_TURN_OFF';

export const FETCH_ROLE_REQUEST = 'FETCH_ROLE_REQUEST';
export const FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS';
export const FETCH_ROLE_ERROR = 'FETCH_ROLE_ERROR';

export const SET_COMPANIES = 'SET_COMPANIES';

export const SET_CURRENT_COMPANY_REQUEST = 'SET_CURRENT_COMPANY_REQUEST';
export const SET_CURRENT_COMPANY_SUCCESS = 'SET_CURRENT_COMPANY_SUCCESS';

export const SET_XUSER_SUCCESS = 'SET_XUSER_SUCCESS';

export const LOGOUT = 'LOGOUT';

export const FETCH_WEBSOCKET_REQUEST = 'FETCH_WEBSOCKET_REQUEST';
export const FETCH_WEBSOCKET_SUCCESS = 'FETCH_WEBSOCKET_SUCCESS';
export const FETCH_WEBSOCKET_ERROR = 'FETCH_WEBSOCKET_ERROR';

export const SET_STATUS_REQUEST = 'SET_STATUS_REQUEST';
export const SET_STATUS_SUCCESS = 'SET_STATUS_SUCCESS';
export const SET_STATUS_ERROR = 'SET_STATUS_ERROR';

export const FETCH_XUSER_REQUEST = 'FETCH_XUSER_REQUEST';
export const FETCH_XUSER_SUCCESS = 'FETCH_XUSER_SUCCESS';

export const SEND_REGISTRATION_FORM_REQUEST = 'SEND_REGISTRATION_FORM_REQUEST';
export const SEND_REGISTRATION_FORM_SUCCESS = 'SEND_REGISTRATION_FORM_SUCCESS';
export const SEND_REGISTRATION_FORM_ERROR = 'SEND_REGISTRATION_FORM_ERROR';

export const SEND_LOGIN_FORM_REQUEST = 'SEND_LOGIN_FORM_REQUEST';
export const SEND_LOGIN_FORM_SUCCESS = 'SEND_LOGIN_FORM_SUCCESS';
export const SEND_LOGIN_FORM_ERROR = 'SEND_LOGIN_FORM_ERROR';

export const SEND_RECOVERY_PWD_REQUEST = 'SEND_RECOVERY_PWD_REQUEST';
export const SEND_RECOVERY_PWD_SUCCESS = 'SEND_RECOVERY_PWD_SUCCESS';
export const SEND_RECOVERY_PWD_ERROR = 'SEND_RECOVERY_PWD_ERROR';

export const SEND_RECOVERY_PWD_TOKEN_REQUEST = 'SEND_RECOVERY_PWD_TOKEN_REQUEST';
export const SEND_RECOVERY_PWD_TOKEN_SUCCESS = 'SEND_RECOVERY_PWD_TOKEN_SUCCESS';
export const SEND_RECOVERY_PWD_TOKEN_ERROR = 'SEND_RECOVERY_PWD_TOKEN_ERROR';

export const FETCH_WIDGET_REQUEST = 'FETCH_WIDGET_REQUEST';
export const FETCH_WIDGET_SUCCESS = 'FETCH_WIDGET_SUCCESS';
export const FETCH_WIDGET_ERROR = 'FETCH_WIDGET_ERROR';